[paths]
benchmarks = "benchmarks"
versions = "versions"
problem = "tesina"
script = "run.py"
venv = "venvs/$interpreter/bin/python"

[execution]
# "all": Indicate all batches
# list: Indicate the prefixes of the batches you want to run (e.g. ["cpython", "numba"])
batches_to_run = "all"

###############################################################################
# CPython - PyPy
###############################################################################


[batches.cpython-0-1-2]
sizes = [256, 512, 1024]
durations = [100]
threads = [1]
executors = [
    { name = "python-0.0", interpreter = "python", label = "CPython Naive" },
    { name = "python-1.0", interpreter = "python", label = "CPython NumPy" },
    { name = "python-2.0", interpreter = "python", label = "CPython NumPy with broadcasting" },
]
[batches.cpython-0-1-2.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.pypy-0-1-2]
sizes = [256, 512, 1024]
durations = [100]
threads = [1]
executors = [
    { name = "python-0.0", interpreter = "pypy", label = "PyPy Naive" },
    { name = "python-1.0", interpreter = "pypy", label = "PyPy NumPy" },
    { name = "python-2.0", interpreter = "pypy", label = "PyPy NumPy with broadcasting" },
]
[batches.pypy-0-1-2.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.cpython-3]
sizes = [256, 512, 1024]
durations = [100]
threads = [1]
executors = [
    { name = "python-3.0", interpreter = "python", label = "BS = 8" },
    { name = "python-3.1", interpreter = "python", label = "BS = 16" },
    { name = "python-3.2", interpreter = "python", label = "BS = 32" },
    { name = "python-3.3", interpreter = "python", label = "BS = 64" },
]
[batches.cpython-3.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.cpython-4]
sizes = [256, 512, 1024]
durations = [100]
threads = [2, 4, 8, 16]
executors = [
    { name = "python-4.0", interpreter = "python", label = "Threading" },
]
[batches.cpython-4.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


###############################################################################
# Numba
###############################################################################

[batches]
[batches.numba-0]
sizes = [4096, 8192, 16384]
durations = [100]
threads = [1]
executors = [
    { name = "python-2.0", interpreter = "python", label = "naive" },
    { name = "numba-0.0", interpreter = "python", label = "njit" },
]
[batches.numba-0.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.numba-1]
sizes = [4096, 8192, 16384]
durations = [100]
threads = [56, 112]
executors = [{ name = "numba-1.0", interpreter = "python", label = "parallel" }]
[batches.numba-1.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.numba-2]
sizes = [16384, 32768, 65536]
durations = [100]
threads = [56, 112]
executors = [
    { name = "numba-1.0", interpreter = "python", label = "parallel" },
    { name = "numba-2.0", interpreter = "python", label = "without broadcasting" },
]
[batches.numba-2.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.numba-3]
sizes = [65536, 131072, 262144]
durations = [100]
threads = [112]
executors = [
    { name = "numba-2.0", interpreter = "python", label = "without broadcasting" },
    { name = "numba-3.0", interpreter = "python", label = "1 / (dsquared ^ 1.5)" },
    { name = "numba-3.1", interpreter = "python", label = "dsquared ^ 1.5" },
    { name = "numba-3.2", interpreter = "python", label = "math.pow" },
    { name = "numba-3.3", interpreter = "python", label = "numpy.power" },
    { name = "numba-3.4", interpreter = "python", label = "avx512" },
]
[batches.numba-3.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.numba-4]
sizes = [65536, 131072, 262144]
durations = [100]
threads = [112]
executors = [
    { name = "numba-2.0", interpreter = "python", label = "without broadcasting" },
    { name = "numba-4.0", interpreter = "python", label = "BS=4" },
    { name = "numba-4.1", interpreter = "python", label = "BS=8" },
    { name = "numba-4.2", interpreter = "python", label = "BS=16" },
    { name = "numba-4.3", interpreter = "python", label = "BS=32" },
    { name = "numba-4.4", interpreter = "python", label = "BS=64" },
]
[batches.numba-4.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.numba-5]
sizes = [65536, 131072, 262144, 524288]
durations = [100]
threads = [112]
executors = [
    { name = "numba-2.0", interpreter = "python", label = "float64 relaxed" },
    { name = "numba-5.0", interpreter = "python", label = "float64 strict" },
    { name = "numba-5.1", interpreter = "python", label = "float32 relaxed" },
    { name = "numba-5.2", interpreter = "python", label = "float32 strict" },
]
[batches.numba-5.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.numba-6]
sizes = [524288]
durations = [100]
threads = [28, 56, 112]
executors = [
    { name = "numba-5.1", interpreter = "python", label = "float32 default" },
    { name = "numba-6.0", interpreter = "python", label = "float32 workqueue" },
    { name = "numba-6.1", interpreter = "python", label = "float32 omp" },
    { name = "numba-6.2", interpreter = "python", label = "float32 threading" },
]
[batches.numba-6.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


###############################################################################
# Cython
###############################################################################

[batches.cython-0]
sizes = [256, 512, 1024]
durations = [100]
threads = [1]
executors = [
    { name = "cython-0.0", interpreter = "python", label = "without typing" },
    { name = "cython-1.0", interpreter = "python", label = "typing" },
]
[batches.cython-0.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.cython-1]
sizes = [4096, 8192, 16384]
durations = [100]
threads = [1]
executors = [
    { name = "cython-1.0", interpreter = "python", label = "-O3" },
    { name = "cython-1.1", interpreter = "python", label = "-O3 -xCORE-AVX512 -qopt-zmm-usage=high" },
    { name = "cython-1.2", interpreter = "python", label = "-O3 -xCORE-AVX512 -qopt-zmm-usage=high -fp-model fast=2" },
    { name = "cython-1.3", interpreter = "python", label = "-O3 -march=native -ffast-math" },
]
[batches.cython-1.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.cython-2a]
sizes = [16384, 32768, 65536]
durations = [100]
threads = [1]
executors = [{ name = "cython-1.3", interpreter = "python", label = "serial" }]
[batches.cython-2a.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.cython-2b]
sizes = [16384, 32768, 65536]
durations = [100]
threads = [56, 112]
executors = [
    { name = "cython-2.0", interpreter = "python", label = "parallel" },
]
[batches.cython-2b.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.cython-3]
sizes = [65536, 131072, 262144]
durations = [100]
threads = [112]
executors = [
    { name = "cython-2.0", interpreter = "python", label = "dsquared ^ -1.5" },
    { name = "cython-3.0", interpreter = "python", label = "1 / (dsquared ^ 1.5)" },
    { name = "cython-3.1", interpreter = "python", label = "dsquared ^ 1.5" },
]
[batches.cython-3.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.cython-4]
sizes = [16384, 32768, 65536]
durations = [100]
threads = [112]
executors = [
    { name = "cython-2.0", interpreter = "python", label = "BS=1" },
    { name = "cython-4.0", interpreter = "python", label = "BS=4" },
    { name = "cython-4.1", interpreter = "python", label = "BS=8" },
    { name = "cython-4.2", interpreter = "python", label = "BS=16" },
    { name = "cython-4.3", interpreter = "python", label = "BS=32" },
    { name = "cython-4.4", interpreter = "python", label = "BS=64" },
]
[batches.cython-4.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.cython-5]
sizes = [65536, 131072, 262144, 524288]
durations = [100]
threads = [112]
executors = [
    { name = "cython-2.0", interpreter = "python", label = "float64 relaxed" },
    { name = "cython-5.0", interpreter = "python", label = "float64 strict" },
    { name = "cython-5.1", interpreter = "python", label = "float32 relaxed" },
    { name = "cython-5.2", interpreter = "python", label = "float32 strict" },
]
[batches.cython-5.plot]
theme = "Paired"
height = 10
width = 10
label = "label"


[batches.cython-6]
sizes = [524288]
durations = [100]
threads = [28, 56, 112]
executors = [
    { name = "cython-5.1", interpreter = "python", label = "float32 static" },
    { name = "cython-6.0", interpreter = "python", label = "float32 dynamic" },
    { name = "cython-6.1", interpreter = "python", label = "float32 guided" },
]
[batches.cython-6.plot]
theme = "Paired"
height = 10
width = 10
label = "label"
